import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from '../layout/Header';
import Banner from "../layout/Banner";
import Filter from "../components/Filter";
import Features from "../layout/Features";
import Reasons from "../layout/Reasons/Reasons";
import Examples from "../layout/Examples";
import Footer from "../layout/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oleo+Script:wght@400;700&family=Space+Grotesk:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
       <Header />
       <Banner />
       <Filter />
       <Features />
       <Reasons />
       <Examples />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
